routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/about', 'HomeController@about');
Route::get('/faq', 'HomeController@faq');
Route::post('/contactUs', 'HomeController@contactUs');

Route::get('/dashboard', 'DashboardController@dashboard');
Route::get('/agents/properties', 'UserAgentController@index');
Route::get('/reservations', 'UserCustomerController@index');
Route::resource('/properties', 'PropertyController');
Route::get('/properties/{id}/book', 'UserCustomerController@showBookPage')->name('properties.book');
Route::post('/properties/{id}/book', 'UserCustomerController@book');
Route::resource('properties.video', 'PropertyVideoController', ['only' => ['store', 'update', 'destroy']]);
Route::post('properties/{property}/photos/{photo}', 'PropertyPhotoController@update');
Route::resource('properties.photos', 'PropertyPhotoController',['only' => ['store', 'update', 'destroy']]);
Route::post('properties/{property}/video/{video}', 'PropertyVideoController@update');

Route::resource('messages', 'UserInboxController',['only' => ['show','index']]);
Route::resource('inbox', 'InboxController',['only' => 'index']);
Route::get('/activities', 'ActivityController@index');
Route::get('/notifications/{id}', 'NotificationController@show')->name('notifications.show');

Route::get('/login/{provider}', 'Auth\LoginController@redirectToProvider')->name('login.social');
Route::get('/login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

app/Http/Controllers/PropertyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\PropertyRequest;
use Auth;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use Illuminate\Http\Request;
use Intervention\Image\ImageManagerStatic as Image;
use Validator;

class PropertyController extends ClientController
{
    /**
     * @var boolean
     */
    protected $propertyAlreadyBooked = false;
    /**
     * Create new PropertyController instance
     *
     * @return void 
     */
    public function __construct(ClientInterface $client)
    {
        parent::__construct($client);
        $this->middleware(['auth','agent'], ['except' => ['show', 'showBookPage','book', 'index'] ]);
    }

    /**
     * Display all properties
     * 
     * @return Response
     */
    public function index(Request $request)
    {
        if(!is_null($request->get('me')))
        {
            $me = Auth::user()->id;
            $properties = $this->displayProperties($me);

            return view('agents.properties')->with('properties', $properties->data);
        }
    	$properties = $this->displayProperties();

    	return view('properties.index')->with('properties', $properties->data);
    }

    /**
     * Property Form for adding new property
     * 
     * @return Response
     */
    public function create()
    {
    	return view('properties.create');
    }

    /**
     * Send fields to saamin api for storing data in database
     * 
     * @param  PropertyRequest $request 
     * @return Response
     */
    public function store(PropertyRequest $request)
    {
    	$newProperty = $this->createProperty($request->all());
        if($newProperty == null){
            return redirect()->back()
                ->withInput()
                ->withErrors('Property name already existing!');
        }
		return redirect("/properties/{$newProperty->data->slug}");
    }

    /**
     * Will display a single property
     * 
     * @param  int $id 
     * @return Response
     */
    public function show($id)
    {
        $property = $this->showOneProperty($id);
        if(Auth::check())
        {
            $this->isPropertyAlreadyBooked($property->data);
        }
        return view('properties.show')
                ->with([
                    'property' => $property->data,
                    'propertyAlreadyBooked' => $this->propertyAlreadyBooked,
                    'new' => false
                ]); 
   }

    /**
     * Edit form for Property
     * 
     * @param  int $id 
     * @return Response
     */
    public function edit($id)
    {
        $property = $this->showOneProperty($id);
        return view('properties.edit')->with('property', $property->data);
    }

    /**
     * Will send updated fields to saamin api
     * 
     * @param  PropertyRequest $request
     * @param  int         $id      
     * @return Response
     */
    public function update(PropertyRequest $request, $slug)
    {
        $property = $this->updateProperty($request->all(), $slug);
        if(isset($property->error)){
            return back()->withErrors($property->error->message);
        }
        return redirect('/properties/'.$slug)->with('success', $property->data->message);
    }

    /**
     * Will send property to saamin api to be archived
     * 
     * @param  [type] $id [description]
     * @return [type]     [description]
     */
    public function destroy($id)
    {
        $property = $this->deleteProperty($id);
        return redirect('/properties')->with('success', $property->data->message);
    }
    /**
     * Will check if property is already booked by a customer
     * 
     * @param  Property $property 
     * @return boolean            
     */
    public function isPropertyAlreadyBooked($property)
    {
        $userProperties = $this->customerProperties(Auth::user()->id);
        foreach($userProperties->data as $userProperty)
        {
            if($userProperty->id == $property->id)
            {
                $this->propertyAlreadyBooked = true;
            }
        }
    }
}

resources/views/properties/layouts/booking-form.blade.php
<div class="row">
    <div class="col-md-12">
        @include('errors.error')
        <div class="card">
            <div class="card-block">
                <form method="GET" action="{{ route('properties.book', $property->slug) }}">
                    <date-pick :property-id="{{ $property->id }}" ></date-pick>
                      @foreach($property->agent->users as $user)
                        <input type="hidden" name="recipient" value="{{$user->email}}">
                      @endforeach
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/properties/layouts/details.blade.php
<div>
    <h5 class="h4">{{$property->name}}</h5>
    <p class="text-muted">Address: {{$property->address}}</p>
    <p class="small text-muted">{{$property->description}}</p>
    <p class="small text-muted">
        <i class="fa fa-credit-card fa-2x" aria-hidden="true"></i> 
         Price: P{{$property->price_formatted}}
    </p>
    <hr>
    <p class="small text-muted">
        <i class="fa fa-cubes fa-2x" aria-hidden="true"></i> 
         Bathrooms:  {{$property->bathrooms}}
    </p>
    <hr>
    <p class="small text-muted">
        <i class="fa fa-bed fa-2x" aria-hidden="true"></i> 
         Bedrooms:  {{$property->bedrooms}}
    </p>
    
    @if(Auth::check())
        @if(Auth::user()->userable_id !=$property->user_agent_id)
            <hr>
            @include('properties.layouts.host')
        @endif
    @endif
</div>

resources/views/properties/layouts/host.blade.php
@foreach($property->agent->users as $user)
    <p class="h6">
        Your Host: {{$user->firstname }} {{ $user->lastname}} 
    </p>
    <p class="small text-muted">Address - {{ $user->address }}</p>
    <div>
        <a href="{{ route('messages.show', $user->id) }}" class="btn btn-sm btn-info">
            Contact Host
        </a>    
    </div>
@endforeach

resources/views/properties/layouts/video.blade.php
@if($new)
    <div class="dz-video-container" style="height: 100%;">
        <form class="dropzone" id="video-dropzone" action="{{url("properties/$property->id/video")}}" method="POST">
            <div class="dz-message" data-dz-message><span>Click or drag the video here for upload.</span></div>
            <input type="hidden" value="{{$property->name}}" id="property_name"> 
        </form>
    </div> 
@else
    @if(!is_null($property->video))
        <div class="embed-responsive embed-responsive-16by9">
            <video class="embed-responsive-item" controls>
                <source src='{{url($property->video->path)}}' type="video/mp4"> 
            </video>
            <input type="hidden" name="" value={{$property->video->id}}>
            @if(Auth::check())
                @if(Auth::user()->userable_type=='App\UserAgent'
                    && Auth::user()->userable_id==$property->user_agent_id)
                    <div class="overlay float-xs-right">
                        <div class="dropdown float-xs-right">
                            <button class="btn main-btn dropdown-toggle" type="button" id="dropdownMenuButton"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-pencil-square-o"></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                              <a class="dropdown-item" href="#" id="upload-video">Update Video</a>
                              <a class="dropdown-item" href="#" data-toggle="modal" data-target="#removeVideoModal">Remove Video</a>
                            </div>
                        </div>
                    </div>
                @endif
            @endif
        </div>
    @else
        <div class="col-md-12">
            <p class="text-xs-center">No videos  uploaded yet.</p>
            @if(Auth::check())
                @if(Auth::user()->userable_type=='App\UserAgent' && Auth::user()->userable_id==$property->user_agent_id)
                    <div class="upload-new-vid-container">
                        <a href="#" id="upload-new-video" class="upload-new-video" data-toggle="modal" data-target="#add-video-modal">
                            Click here to upload a new video
                        </a>
                    </div>
                @endif
            @endif
        </div>
    @endif
@endif