routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/about', 'HomeController@about');
Route::get('/faq', 'HomeController@faq');
Route::post('/contactUs', 'HomeController@contactUs');

Route::get('/dashboard', 'DashboardController@dashboard');
Route::get('/agents/properties', 'UserAgentController@index');
Route::get('/reservations', 'UserCustomerController@index');
Route::resource('/properties', 'PropertyController');
Route::get('/properties/{id}/book', 'UserCustomerController@showBookPage')->name('properties.book');
Route::post('/properties/{id}/book', 'UserCustomerController@book');
Route::resource('properties.video', 'PropertyVideoController', ['only' => ['store', 'update', 'destroy']]);
Route::post('properties/{property}/photos/{photo}', 'PropertyPhotoController@update');
Route::resource('properties.photos', 'PropertyPhotoController',['only' => ['store', 'update', 'destroy']]);
Route::post('properties/{property}/video/{video}', 'PropertyVideoController@update');

Route::resource('messages', 'UserInboxController',['only' => ['show','index']]);
Route::resource('inbox', 'InboxController',['only' => 'index']);
Route::get('/activities', 'ActivityController@index');
Route::get('/notifications/{id}', 'NotificationController@show')->name('notifications.show');

Route::get('/login/{provider}', 'Auth\LoginController@redirectToProvider')->name('login.social');
Route::get('/login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

resources/views/layouts/footer.blade.php
<footer class="container-fluid pt-5 pb-5">
    <div class="row">
    	<div class="col pt-4 text-left">
    		<p class="fa fa-copyright" aria-hidden="true"></p> 
    		<script type="text/javascript">
    		var d = new Date()
    		document.write(d.getFullYear())
    		</script>|<a href="http://www.4ksoftware.io" class="text-danger" target="_blank">
    		FOUR K SOFTWARE</a> | ALL RIGHTS RESERVED 	
      	</div>
        <div class="footer-social col text-right">
            <ul class="social-network social-circle ">
                <li>
                    <a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook fa-lg"></i></a>
                </li>
                <li>
                    <a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter fa-lg"></i></a>
                </li>
                <li>
                    <a href="#" class="icoGoogle" title="Google +"><i class="fa fa-google-plus fa-lg"></i></a>
                </li>
            </ul>               
        </div>
    </div>
</footer>

resources/views/layouts/header.blade.php
<header>
    <nav class="navbar navbar-toggleable-sm navbar-light bg-warning">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{{ url('/') }}">SAAMIN</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link " href="{{ route('properties.index') }}">Properties</a>
                </li>
            </ul>

            <!-- Button trigger modal -->   
            <ul class="navbar-nav">
                @if(Auth::check())
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Notifications<span class="tag tag-danger" v-if="notifications.unread_notifications"> @{{ countNotifications }}</span>
                        </a>
                        <div class="dropdown-menu" >
                            <p class="text-center">Latest Notifications</p>
                            <div class="dropdown-divider"></div>
                            <div v-for="notification in notifications.notifications">
                                <a class="dropdown-item" @click="viewNotification(notification.id)">@{{ notification.data.message }}</a>
                            </div>
                        </div>
                    </li>
                    <messages-header :id="id"></messages-header>
                @endif
                @if(Auth::guest())
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('register') }}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a href="/login" class="nav-link">Log In</a>
                    </li>
                @else
                    <li class="nav-item dropdown">  
                        <a class="nav-link dropdown-toggle userImg" role="button" data-toggle="dropdown">
                            <img src="{{ Auth::user()->avatar }}">{{Auth::user()->firstname}} {{Auth::user()->lastname}}
                        </a>
                        <div class="dropdown-menu ">
                            <a href="{{ url('/dashboard') }}" class="dropdown-item">My Dashboard</a>
                            @if(Auth::user()->userable_type == 'App\UserCustomer')
                                <a href="{{ url('/reservations') }}" class="dropdown-item">Reservations</a>
                            @else
                                <a href="{{ url('/properties?me') }}" class="dropdown-item">My Properties</a>
                            @endif
                            <div class="dropdown-divider"></div>                            
                            <a href="{{ url('/logout') }}"
                                onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();" class="dropdown-item text-xs-center"><i class="fa fa-sign-out" aria-hidden="true"></i>&nbsp;Log Out
                            </a>
                            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </div>
                    </li>
                @endif
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="api-key" content="{{ config('api.api_key')}}">
    <meta name="app-id" content="{{ config('api.app_id') }}">
    <meta name="alg-table" content="{{ config('api.alg_env') }}">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    @yield('title')

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token()
        ]); ?>
    </script>
    <script>
        @if(Auth::check())
            let currentlyLogin = <?php echo json_encode(auth()->user()->id); ?>;
        @endif
    </script>

	<!-- Bootstrap Production -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/instantsearch.js/1/instantsearch.min.css">

    <!-- Bootstrap Local -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="/css/main.css">
	<link rel="stylesheet" type="text/css" href="/css/animate.css">
    
    <link rel="stylesheet" type="text/css" href="/css/dropzone.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="stylesheet" type="text/css" href="/css/app.css">

	@yield('stylesheets')

</head>
<body>
	@include('layouts.header')
	
    @yield('content')
    @include('layouts.footer')

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script> 
    <script src="/js/dropzone.min.js"></script>
    <script src='/js/main.js'></script>

    @yield('scripts')
</body>
</html>